impl_rule: |
  # 実装ルール（可読性基準）

  1. 関数は原則 35 行以内、超える場合は貴務で分割。
  2. if はカード節優先で、ネストは最大2段まで。
  3. 変数名、関数名は長すぎる場合は、基本はMax3ワードまで、シンプルな表現を用いる。
  4. 連切な改行を行う。
  5. KISS/DRY/リーダブルコードの原則を守る

task:
  - id: '38'
    url: '-'
    title: '-'
    action: |-
      Task Manager というタイトルに色を付けたい。今はグレーなので殺風景です
      ただしあまり目立たない色がいい
  - id: '39'
    url: '-'
    title: '-'
    action: |
      起動するPort番号は5555にする。5174だとかぶるので変えたい
  - id: '40'
    url: '-'
    title: '-'
    action: |-
      新規タスク表示部に左側に少し余白をつけたい
      スペース２つ分ぐらい
  - id: '41'
    url: '-'
    title: '-'
    action: |-
      タイトル部は余白を少し狭く
      メインタイトルの文字の大きさを少し小さく
  - id: '42'
    url: '-'
    title: '-'
    action: |-
      プロジェクト画面で表にカーソルがあってしまい、大きなカーソルが表示されてしまい気になる
  - id: '43'
    url: '-'
    title: '-'
    action: |-
      TOP画面にSetting画面を追加したい

      Setting画面の機能

       - データエクスポート/インポート機能(projects.yml)
  - id: '44'
    url: '-'
    title: '-'
    action: |
      プロジェクト新規作成画面

      New Projectでなく新規作成に名称変更
