task:
  - id: '113'
    url: '-'
    title: '-'
    action: |-
      タスクについて、TODO、DONEがあるが、PENDING(薄黄色)とCANCEL(グレー)という状態を新たに追加したい。

      これらの状態はタスクの編集画面の更新、Cancelボタンと同じ行で設定できるようにしたい。
  - id: '114'
    url: '-'
    title: '-'
    action: |
      固定ヘッダの色を今の倍に増やして。暗めの色がいいです。任意の色も変更できるといいです
